demo/quota:
  url: "/quota"
  policy: "demo/quota"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties: {}
demo/demo:
  url: "/demo"
  policy: "demo/demo"
  httpMethods:
  - "DELETE"
  - "POST"
  - "GET"
  - "PUT"
  properties:
    servicePropColor: "green"
